// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  services: [{type: 'autogenerated', dirName: 'services'}],
  feedback: [{type: 'autogenerated', dirName: 'feedback'}],
  rooadmap: [{type: 'autogenerated', dirName: 'rooadmap'}],
};

module.exports = sidebars;
